# Generated by Django 6.1.1 on 2026-09-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_registration_invitation"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Multi-tenancy scaffolding (Stage 13.5). Single-school deployments can leave this null; it is resolved to the default school on save.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="core.school",
            ),
        ),
        # NOTE: `RegistrationInvitation` (added in 0003) is intentionally left
        # in place rather than deleted here, even though it isn't referenced
        # by models.py right now. It's an activation-token model that was
        # apparently a prior, abandoned attempt at exactly the provisioning
        # flow Stage 3 needs (admin approves -> token generated -> email ->
        # user sets password). Rather than drop it and rebuild an equivalent
        # model from scratch in Stage 3, Stage 3 should inspect and likely
        # resurrect this one. See GAP_ANALYSIS_AND_ROADMAP.md.
    ]
