# Generated by Django 6.1.1 on 2026-09-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("applicant", "Applicant"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registrationinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("applicant", "Applicant"),
                ],
                max_length=20,
            ),
        ),
    ]
