# Generated by Django 6.1.1 on 2026-09-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_classschedule"),
        ("accounts", "0005_alter_profile_role_alter_registrationinvitation_role"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("student_registered", "Student Registered"),
                            ("application_submitted", "Application Submitted"),
                            ("document_uploaded", "Document Uploaded"),
                            ("payment_completed", "Payment Completed"),
                            ("application_updated", "Application Updated"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortalNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(default="general", max_length=30),
                ),
                ("link", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="Custom student identifier if assigned before enrollment",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["student_id"], name="accounts_pr_student_fb264f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["email_verification_token"],
                name="accounts_pr_email_v_304f0a_idx",
            ),
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portalnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["is_read", "-created_at"], name="accounts_ad_is_read_85b7e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["notification_type"], name="accounts_ad_notific_0b1ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portalnotification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="accounts_po_user_id_0a780e_idx",
            ),
        ),
    ]
