# Generated by Django 5.2.17 on 2026-09-04 07:22

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_number", models.CharField(max_length=32, unique=True)),
                ("dob", models.DateField(validators=[students.models.validate_dob])),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["admission_number"],
                        name="students_st_admissi_321db4_idx",
                    )
                ],
            },
        ),
    ]
