# Generated by Django 6.1.1 on 2026-09-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataQualityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("overall_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "student_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "attendance_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "finance_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("academic_year", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="DimDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("is_weekend", models.BooleanField()),
                ("term", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DimStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField(unique=True)),
                ("admission_number", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("dob", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DimTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FactAcademicPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("graded_at", models.DateField()),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimstudent",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimsubject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimstudent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.dimstudent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="uniq_fact_attendance"
                    )
                ],
            },
        ),
    ]
