# Generated by Django 6.1.1 on 2026-09-07 20:50

import admissions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Application Started"),
                            ("submitted", "Application Submitted"),
                            ("documents_pending", "Documents Pending"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("under_review", "Under Review"),
                            ("assessment_scheduled", "Assessment Scheduled"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("info_required", "Additional Information Required"),
                            ("waitlisted", "Waitlisted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("admission_offered", "Admission Offered"),
                            ("enrollment_pending", "Enrollment Pending"),
                            ("enrolled", "Enrolled"),
                        ],
                        default="started",
                        max_length=25,
                    ),
                ),
                ("student_first_name", models.CharField(max_length=100)),
                ("student_middle_name", models.CharField(blank=True, max_length=100)),
                ("student_last_name", models.CharField(max_length=100)),
                ("student_dob", models.DateField()),
                ("student_gender", models.CharField(blank=True, max_length=20)),
                ("student_nationality", models.CharField(blank=True, max_length=100)),
                ("student_phone", models.CharField(blank=True, max_length=30)),
                ("student_email", models.EmailField(blank=True, max_length=254)),
                ("student_address", models.CharField(blank=True, max_length=255)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("previous_class", models.CharField(blank=True, max_length=100)),
                ("class_applying_for", models.CharField(max_length=100)),
                ("academic_session", models.CharField(max_length=20)),
                ("guardian_full_name", models.CharField(max_length=200)),
                ("guardian_relationship", models.CharField(max_length=100)),
                ("guardian_phone", models.CharField(max_length=30)),
                ("guardian_email", models.EmailField(max_length=254)),
                ("guardian_address", models.CharField(blank=True, max_length=255)),
                ("decision_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("previous_report", "Previous School Report"),
                            ("passport_photo", "Passport Photograph"),
                            ("identification", "Identification Document"),
                            ("medical", "Medical Document"),
                            ("other", "Other Supporting Document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=admissions.models.admission_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="admissions.admissionapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
