# Generated by Django 6.1.1 on 2026-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_parentrelationshiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondocument',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('previous_report', 'Previous School Report'), ('passport_photo', 'Passport Photograph'), ('identification', 'Identification Document'), ('medical', 'Medical Document'), ('payment_receipt', 'Payment Receipt / Bank Slip'), ('other', 'Other Supporting Document')], max_length=30),
        ),
    ]
