# Generated by Django 6.1.1 on 2026-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admissiondocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total admission and tuition fee amount due', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='fee_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Itemized fee breakdown: tuition, development, lab, books, etc.'),
        ),
    ]
