# Generated by Django 6.1.1 on 2026-09-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-id']},
        ),
    ]
