# Generated by Django 6.1.1 on 2026-09-23 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff')], default='teacher', max_length=20)),
                ('department', models.CharField(default='Academics', max_length=100)),
                ('date', models.DateField()),
                ('check_in_time', models.CharField(default='07:45 AM', max_length=20)),
                ('check_out_time', models.CharField(default='03:00 PM', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=7.5, max_digits=4)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave'), ('half_day', 'Half Day'), ('remote', 'Remote'), ('excused', 'Excused')], default='present', max_length=20)),
                ('late_minutes', models.IntegerField(default=0)),
                ('leave_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user__id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_staff_attendance_user_day')],
            },
        ),
    ]
