// Realistic populated data for all 18 Riverside Academy Administration Modules

export const INITIAL_STUDENTS = [
  {
    id: 1,
    name: 'Chinedu Okafor',
    email: 'chinedu.okafor@student.riversideacademy.com',
    student_id: 'RS-0001',
    class: 'JSS 1',
    gender: 'Male',
    age: 12,
    dob: '2012-05-14',
    guardian: {
      name: 'Mr. Okafor',
      phone: '0803 123 4567',
      relationship: 'Father',
      email: 'okafor@parent.riversideacademy.com',
      address: '12, Unity Street, Owerri, Imo State',
    },
    attendance: 96,
    fee_status: 'Paid',
    enrolled_on: '2024-09-02',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    grades: [
      { subject: 'Mathematics', score: 88, grade: 'A' },
      { subject: 'English Language', score: 92, grade: 'A' },
      { subject: 'Basic Science', score: 85, grade: 'A' },
      { subject: 'Social Studies', score: 79, grade: 'B' },
    ],
  },
  {
    id: 2,
    name: 'Amaka Nwosu',
    email: 'amaka.nwosu@student.riversideacademy.com',
    student_id: 'RS-0002',
    class: 'JSS 2',
    gender: 'Female',
    age: 13,
    dob: '2011-08-20',
    guardian: {
      name: 'Mrs. Nwosu',
      phone: '0806 234 5678',
      relationship: 'Mother',
      email: 'nwosu@parent.riversideacademy.com',
      address: '45, Palm Avenue, Victoria Island, Lagos',
    },
    attendance: 92,
    fee_status: 'Partial',
    enrolled_on: '2024-09-05',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    grades: [
      { subject: 'Mathematics', score: 74, grade: 'B' },
      { subject: 'English Language', score: 86, grade: 'A' },
      { subject: 'Civic Education', score: 80, grade: 'A' },
    ],
  },
  {
    id: 3,
    name: 'Tunde Bello',
    email: 'tunde.bello@student.riversideacademy.com',
    student_id: 'RS-0003',
    class: 'SS 1',
    gender: 'Male',
    age: 15,
    dob: '2009-03-11',
    guardian: {
      name: 'Mr. Bello',
      phone: '0703 987 6543',
      relationship: 'Father',
      email: 'bello@parent.riversideacademy.com',
      address: '8, Commercial Road, Ikeja, Lagos',
    },
    attendance: 88,
    fee_status: 'Paid',
    enrolled_on: '2024-08-28',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    grades: [
      { subject: 'Physics', score: 78, grade: 'B' },
      { subject: 'Chemistry', score: 82, grade: 'A' },
      { subject: 'Further Mathematics', score: 85, grade: 'A' },
    ],
  },
  {
    id: 4,
    name: 'Bisola Adebayo',
    email: 'bisola.adebayo@student.riversideacademy.com',
    student_id: 'RS-0004',
    class: 'JSS 3',
    gender: 'Female',
    age: 14,
    dob: '2010-11-25',
    guardian: {
      name: 'Mrs. Adebayo',
      phone: '0809 876 5432',
      relationship: 'Mother',
      email: 'adebayo@parent.riversideacademy.com',
      address: '19, Hilltop Estate, Abuja',
    },
    attendance: 100,
    fee_status: 'Paid',
    enrolled_on: '2024-09-01',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    grades: [
      { subject: 'Mathematics', score: 95, grade: 'A' },
      { subject: 'English', score: 94, grade: 'A' },
    ],
  },
  {
    id: 5,
    name: 'Emeka Uche',
    email: 'emeka.uche@student.riversideacademy.com',
    student_id: 'RS-0005',
    class: 'SS 2',
    gender: 'Male',
    age: 16,
    dob: '2008-01-19',
    guardian: {
      name: 'Mr. Uche',
      phone: '0706 345 6789',
      relationship: 'Father',
      email: 'uche@parent.riversideacademy.com',
      address: '22, Marina Road, Port Harcourt',
    },
    attendance: 76,
    fee_status: 'Pending',
    enrolled_on: '2024-09-03',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    grades: [
      { subject: 'Biology', score: 62, grade: 'C' },
      { subject: 'Economics', score: 68, grade: 'B' },
    ],
  },
]

export const INITIAL_TEACHERS = [
  {
    id: 1,
    name: 'Mr. James Okafor',
    title: 'Senior Teacher',
    employee_id: 'TCH001',
    subject: 'Mathematics',
    department: 'Sciences',
    classes: ['JSS 1', 'JSS 2', 'SS 1'],
    attendance: 96,
    status: 'Active',
    phone: '+234 802 345 6789',
    email: 'james.okafor@staff.riversideacademy.com',
    location: 'Block A, Room 04',
    joined: 'Jan 15, 2018 (6 years)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    schedule: [
      { day: 'Mon', time: '8:00 - 10:00', class: 'JSS 1 (Math)' },
      { day: 'Wed', time: '10:30 - 12:30', class: 'SS 1 (Further Math)' },
      { day: 'Fri', time: '8:00 - 10:00', class: 'JSS 2 (Math)' },
    ],
  },
  {
    id: 2,
    name: 'Mrs. Adeola Bello',
    title: 'Head of Department',
    employee_id: 'TCH002',
    subject: 'English Language',
    department: 'Arts',
    classes: ['JSS 1', 'JSS 3', 'SS 2'],
    attendance: 98,
    status: 'Active',
    phone: '+234 803 123 4567',
    email: 'adeola.bello@staff.riversideacademy.com',
    location: 'Block C, Room 12',
    joined: 'Aug 12, 2019 (5 years)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    schedule: [
      { day: 'Mon', time: '8:00 - 10:00', class: 'JSS 1 (English)' },
      { day: 'Tue', time: '10:30 - 12:30', class: 'SS 2 (Literature)' },
      { day: 'Wed', time: '8:00 - 10:00', class: 'JSS 3 (English)' },
      { day: 'Thu', time: '10:30 - 12:30', class: 'SS 2 (Literature)' },
      { day: 'Fri', time: '8:00 - 10:00', class: 'JSS 1 (English)' },
    ],
  },
  {
    id: 3,
    name: 'Mr. Chinedu Nwosu',
    title: 'Teacher',
    employee_id: 'TCH003',
    subject: 'Physics',
    department: 'Sciences',
    classes: ['SS 1', 'SS 2'],
    attendance: 94,
    status: 'Active',
    phone: '+234 805 678 9012',
    email: 'chinedu.nwosu@staff.riversideacademy.com',
    location: 'Block B, Room 08',
    joined: 'Sep 01, 2021 (3 years)',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    schedule: [
      { day: 'Tue', time: '8:00 - 10:00', class: 'SS 1 (Physics)' },
      { day: 'Thu', time: '8:00 - 10:00', class: 'SS 2 (Physics Lab)' },
    ],
  },
  {
    id: 4,
    name: 'Mrs. Funke Ibrahim',
    title: 'Teacher',
    employee_id: 'TCH004',
    subject: 'Biology',
    department: 'Sciences',
    classes: ['JSS 2', 'SS 1'],
    attendance: 92,
    status: 'Active',
    phone: '+234 807 890 1234',
    email: 'funke.ibrahim@staff.riversideacademy.com',
    location: 'Block B, Room 03',
    joined: 'Feb 10, 2020 (4 years)',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    schedule: [
      { day: 'Mon', time: '10:30 - 12:30', class: 'JSS 2 (Basic Science)' },
      { day: 'Wed', time: '10:30 - 12:30', class: 'SS 1 (Biology)' },
    ],
  },
  {
    id: 5,
    name: 'Mr. Samuel Adeyemi',
    title: 'Teacher',
    employee_id: 'TCH005',
    subject: 'Chemistry',
    department: 'Sciences',
    classes: ['SS 1', 'SS 2'],
    attendance: 90,
    status: 'Active',
    phone: '+234 808 901 2345',
    email: 'samuel.adeyemi@staff.riversideacademy.com',
    location: 'Block B, Lab 2',
    joined: 'Nov 05, 2022 (2 years)',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    schedule: [
      { day: 'Tue', time: '10:30 - 12:30', class: 'SS 1 (Chemistry)' },
      { day: 'Thu', time: '10:30 - 12:30', class: 'SS 2 (Chemistry Lab)' },
    ],
  },
  {
    id: 6,
    name: 'Mr. Bola Akinola',
    title: 'Teacher',
    employee_id: 'TCH009',
    subject: 'Computer Science',
    department: 'ICT',
    classes: ['JSS 3', 'SS 2'],
    attendance: 87,
    status: 'On Leave',
    phone: '+234 809 012 3456',
    email: 'bola.akinola@staff.riversideacademy.com',
    location: 'ICT Innovation Hub',
    joined: 'Sep 15, 2023 (1 year)',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    schedule: [],
  },
]

export const INITIAL_PARENTS = [
  {
    id: 1,
    name: 'Mr. Chukwuma Okafor',
    phone: '0803 123 4567',
    email: 'okafor@parent.riversideacademy.com',
    relationship: 'Father',
    children: [
      { name: 'Chinedu Okafor', class: 'JSS 1', id: 'RS-0001' }
    ],
    outstanding_fees: 0,
    last_activity: '2 hours ago',
    status: 'Active',
    address: '12, Unity Street, Owerri, Imo State',
  },
  {
    id: 2,
    name: 'Mrs. Ngozi Nwosu',
    phone: '0806 234 5678',
    email: 'nwosu@parent.riversideacademy.com',
    relationship: 'Mother',
    children: [
      { name: 'Amaka Nwosu', class: 'JSS 2', id: 'RS-0002' }
    ],
    outstanding_fees: 45000,
    last_activity: 'Yesterday',
    status: 'Active',
    address: '45, Palm Avenue, Victoria Island, Lagos',
  },
  {
    id: 3,
    name: 'Mr. Olumide Bello',
    phone: '0703 987 6543',
    email: 'bello@parent.riversideacademy.com',
    relationship: 'Father',
    children: [
      { name: 'Tunde Bello', class: 'SS 1', id: 'RS-0003' }
    ],
    outstanding_fees: 0,
    last_activity: '3 days ago',
    status: 'Active',
    address: '8, Commercial Road, Ikeja, Lagos',
  },
  {
    id: 4,
    name: 'Mrs. Folake Adebayo',
    phone: '0809 876 5432',
    email: 'adebayo@parent.riversideacademy.com',
    relationship: 'Mother',
    children: [
      { name: 'Bisola Adebayo', class: 'JSS 3', id: 'RS-0004' }
    ],
    outstanding_fees: 0,
    last_activity: '5 days ago',
    status: 'Active',
    address: '19, Hilltop Estate, Abuja',
  },
  {
    id: 5,
    name: 'Mr. Gabriel Uche',
    phone: '0706 345 6789',
    email: 'uche@parent.riversideacademy.com',
    relationship: 'Father',
    children: [
      { name: 'Emeka Uche', class: 'SS 2', id: 'RS-0005' }
    ],
    outstanding_fees: 150000,
    last_activity: '1 week ago',
    status: 'Active',
    address: '22, Marina Road, Port Harcourt',
  },
]

export const INITIAL_STAFF = [
  { id: 1, employee_id: 'STF001', name: 'Alhaji Musa Danjuma', department: 'Administrative', position: 'Registrar', phone: '0802 111 2222', email: 'musa.danjuma@staff.riversideacademy.com', status: 'Active', attendance: 98 },
  { id: 2, employee_id: 'STF002', name: 'Mrs. Grace Okonjo', department: 'Finance', position: 'Chief Bursar', phone: '0803 222 3333', email: 'grace.okonjo@staff.riversideacademy.com', status: 'Active', attendance: 99 },
  { id: 3, employee_id: 'STF003', name: 'Mr. Sunday Eze', department: 'IT', position: 'Systems Administrator', phone: '0805 333 4444', email: 'sunday.eze@staff.riversideacademy.com', status: 'Active', attendance: 95 },
  { id: 4, employee_id: 'STF004', name: 'Dr. (Mrs) Ngozi Obi', department: 'Medical', position: 'School Physician', phone: '0807 444 5555', email: 'ngozi.obi@staff.riversideacademy.com', status: 'Active', attendance: 94 },
  { id: 5, employee_id: 'STF005', name: 'Mr. Ibrahim Usman', department: 'Security', position: 'Chief Security Officer', phone: '0808 555 6666', email: 'ibrahim.usman@staff.riversideacademy.com', status: 'Active', attendance: 100 },
  { id: 6, employee_id: 'STF006', name: 'Mr. Patrick Abiola', department: 'Maintenance', position: 'Facilities Manager', phone: '0809 666 7777', email: 'patrick.abiola@staff.riversideacademy.com', status: 'Active', attendance: 91 },
]

export const INITIAL_CLASSES = [
  { id: 1, name: 'JSS 1', code: 'JSS1-A', class_teacher: 'Mr. James Okafor', students_count: 52, capacity: 55, room: 'Block A, Room 01', attendance: 96, subjects_count: 12 },
  { id: 2, name: 'JSS 2', code: 'JSS2-A', class_teacher: 'Mrs. Funke Ibrahim', students_count: 48, capacity: 50, room: 'Block A, Room 02', attendance: 92, subjects_count: 12 },
  { id: 3, name: 'JSS 3', code: 'JSS3-A', class_teacher: 'Mrs. Adeola Bello', students_count: 46, capacity: 50, room: 'Block A, Room 03', attendance: 94, subjects_count: 14 },
  { id: 4, name: 'SS 1', code: 'SS1-SCI', class_teacher: 'Mr. Chinedu Nwosu', students_count: 42, capacity: 45, room: 'Block B, Room 01', attendance: 93, subjects_count: 9 },
  { id: 5, name: 'SS 2', code: 'SS2-SCI', class_teacher: 'Mr. Samuel Adeyemi', students_count: 41, capacity: 45, room: 'Block B, Room 02', attendance: 89, subjects_count: 9 },
  { id: 6, name: 'SS 3', code: 'SS3-ALL', class_teacher: 'Mr. Bola Akinola', students_count: 38, capacity: 40, room: 'Block B, Room 03', attendance: 97, subjects_count: 9 },
]

export const INITIAL_EVENTS = [
  { id: 1, date_month: 'SEP', date_day: '18', title: 'Parent-Teacher Meeting', time: '9:00 AM – 12:00 PM', location: 'Main Auditorium', type: 'Parent Meeting', status: 'Upcoming', badge: 'Upcoming' },
  { id: 2, date_month: 'SEP', date_day: '20', title: 'Mid-Term Examination', time: '8:00 AM – 2:00 PM', location: 'All Classes', type: 'Examination', status: 'Upcoming', badge: 'Upcoming' },
  { id: 3, date_month: 'SEP', date_day: '25', title: 'School Assembly', time: '9:00 AM – 10:30 AM', location: 'Main Hall', type: 'Assembly', status: 'Upcoming', badge: 'Upcoming' },
  { id: 4, date_month: 'SEP', date_day: '28', title: 'Fees Payment Deadline', time: 'All Day', location: 'Finance Office', type: 'Fee Deadline', status: 'Important', badge: 'Important' },
  { id: 5, date_month: 'OCT', date_day: '01', title: 'Independence Day Holiday', time: 'All Day', location: 'National Holiday', type: 'Holiday', status: 'Upcoming', badge: 'Upcoming' },
]

export const INITIAL_ACTIVITIES = [
  { id: 1, user: 'Chinedu Okafor', action: 'New student admitted', detail: 'Class JSS 1', time: '2 hours ago', icon: 'user', color: '#16a34a' },
  { id: 2, user: 'Adaeze Eze', action: 'Fee payment received', detail: 'SS 2 — ₦150,000', time: '3 hours ago', icon: 'wallet', color: '#2563eb' },
  { id: 3, user: 'JSS 3A Class', action: 'Attendance updated', detail: '92% present recorded', time: '4 hours ago', icon: 'check', color: '#059669' },
  { id: 4, user: 'Mr. James Wilson', action: 'New teacher added', detail: 'Mathematics Department', time: '5 hours ago', icon: 'user', color: '#8b5cf6' },
  { id: 5, user: 'Mrs. Ngozi Chukwuma', action: 'Parent registered', detail: 'Linked to 2 children', time: '6 hours ago', icon: 'users', color: '#ec4899' },
]

export const INITIAL_ALERTS = [
  { id: 1, title: 'Low attendance in JSS 2B', detail: '78% attendance rate (below 85% benchmark)', severity: 'urgent', color: '#dc2626', time: '1 hour ago' },
  { id: 2, title: 'Fee payment pending', detail: '12 students have outstanding term fees', severity: 'warning', color: '#d97706', time: '3 hours ago' },
  { id: 3, title: 'New admission applications', detail: '5 pending applications need review', severity: 'info', color: '#2563eb', time: '4 hours ago' },
  { id: 4, title: 'System backup completed', detail: 'All database records backed up successfully', severity: 'success', color: '#16a34a', time: '6 hours ago' },
]

export const INITIAL_CANDIDATES = [
  {
    id: 1,
    app_no: 'ADM-2025-001',
    name: 'Somtochukwu Obi',
    email: 'somto.obi@candidate.riversideacademy.com',
    applied_class: 'JSS 1',
    gender: 'Male',
    parent_name: 'Dr. Chidi Obi',
    parent_phone: '0802 999 1122',
    stage: 'Under Review',
    entrance_score: 84,
    status: 'Pending',
    applied_date: '2025-08-14',
    documents_verified: true,
  },
  {
    id: 2,
    app_no: 'ADM-2025-002',
    name: 'Zainab Danjuma',
    email: 'zainab.danjuma@candidate.riversideacademy.com',
    applied_class: 'JSS 1',
    gender: 'Female',
    parent_name: 'Alhaji Danjuma',
    parent_phone: '0803 888 2233',
    stage: 'Interview',
    entrance_score: 91,
    status: 'Scheduled',
    applied_date: '2025-08-16',
    documents_verified: true,
  },
  {
    id: 3,
    app_no: 'ADM-2025-003',
    name: 'Kelechi Eze',
    email: 'kelechi.eze@candidate.riversideacademy.com',
    applied_class: 'SS 1',
    gender: 'Male',
    parent_name: 'Chief Eze',
    parent_phone: '0805 777 3344',
    stage: 'Accepted',
    entrance_score: 79,
    status: 'Approved',
    applied_date: '2025-08-10',
    documents_verified: true,
  },
  {
    id: 4,
    app_no: 'ADM-2025-004',
    name: 'Fatimah Aliyu',
    email: 'fatimah.aliyu@candidate.riversideacademy.com',
    applied_class: 'JSS 2',
    gender: 'Female',
    parent_name: 'Mrs. Aliyu',
    parent_phone: '0807 666 4455',
    stage: 'Applied',
    entrance_score: 68,
    status: 'New',
    applied_date: '2025-08-22',
    documents_verified: false,
  },
  {
    id: 5,
    app_no: 'ADM-2025-005',
    name: 'Tobi Ogunleye',
    email: 'tobi.ogunleye@candidate.riversideacademy.com',
    applied_class: 'SS 2',
    gender: 'Male',
    parent_name: 'Engr. Ogunleye',
    parent_phone: '0809 555 6677',
    stage: 'Enrolled',
    entrance_score: 88,
    status: 'Completed',
    applied_date: '2025-08-01',
    documents_verified: true,
  },
]

export const INITIAL_FEES_INVOICES = [
  { id: 1, invoice_no: 'INV-2025-001', student_name: 'Chinedu Okafor', class: 'JSS 1', term: 'First Term 2025/2026', amount: 350000, paid: 350000, balance: 0, status: 'Paid', date: '2025-09-02' },
  { id: 2, invoice_no: 'INV-2025-002', student_name: 'Amaka Nwosu', class: 'JSS 2', term: 'First Term 2025/2026', amount: 350000, paid: 305000, balance: 45000, status: 'Partial', date: '2025-09-04' },
  { id: 3, invoice_no: 'INV-2025-003', student_name: 'Tunde Bello', class: 'SS 1', term: 'First Term 2025/2026', amount: 380000, paid: 380000, balance: 0, status: 'Paid', date: '2025-09-01' },
  { id: 4, invoice_no: 'INV-2025-004', student_name: 'Bisola Adebayo', class: 'JSS 3', term: 'First Term 2025/2026', amount: 360000, paid: 360000, balance: 0, status: 'Paid', date: '2025-09-03' },
  { id: 5, invoice_no: 'INV-2025-005', student_name: 'Emeka Uche', class: 'SS 2', term: 'First Term 2025/2026', amount: 380000, paid: 230000, balance: 150000, status: 'Pending', date: '2025-09-05' },
]

export const INITIAL_TIMETABLE = {
  'JSS 1': [
    { period: '8:00 - 8:45 AM', mon: 'Mathematics (Mr. James)', tue: 'English Language (Mrs. Adeola)', wed: 'Basic Science (Mrs. Funke)', thu: 'Social Studies', fri: 'Physical Ed' },
    { period: '8:45 - 9:30 AM', mon: 'Mathematics (Mr. James)', tue: 'English Language (Mrs. Adeola)', wed: 'Basic Science (Mrs. Funke)', thu: 'Civic Education', fri: 'Computer Studies' },
    { period: '9:30 - 10:15 AM', mon: 'English Language', tue: 'Mathematics', wed: 'French Language', thu: 'Agricultural Science', fri: 'Music & Creative Arts' },
    { period: '10:15 - 10:45 AM', mon: 'BREAK / RECESS', tue: 'BREAK / RECESS', wed: 'BREAK / RECESS', thu: 'BREAK / RECESS', fri: 'BREAK / RECESS' },
    { period: '10:45 - 11:30 AM', mon: 'Basic Technology', tue: 'Business Studies', wed: 'Christian Rel. Studies', thu: 'Mathematics', fri: 'Library / Reading' },
    { period: '11:30 - 12:15 PM', mon: 'Social Studies', tue: 'Basic Technology', wed: 'Physical Ed', thu: 'English Language', fri: 'Clubs & Societies' },
    { period: '12:15 - 1:00 PM', mon: 'Computer Studies', tue: 'Civic Education', wed: 'Home Economics', thu: 'Basic Science', fri: 'School Assembly' },
  ]
}

export const INITIAL_NEWS = [
  {
    id: 1,
    title: 'Resumption for Academic Year 2025/2026',
    date: 'Sep 01, 2025',
    category: 'Academic',
    audience: 'All',
    summary: 'Riverside Academy welcomes all returning students and fresh intakes for the 2025/2026 academic calendar.',
    author: 'Office of the Principal',
  },
  {
    id: 2,
    title: 'Mid-Term Break Schedule & Continuous Assessment',
    date: 'Sep 10, 2025',
    category: 'Exams',
    audience: 'Parents & Students',
    summary: 'Mid-term examinations will commence on Sep 20th. Parents are kindly reminded to ensure all term fees are up to date.',
    author: 'Vice Principal (Academics)',
  },
  {
    id: 3,
    title: 'Annual Inter-House Sports Competition',
    date: 'Sep 14, 2025',
    category: 'Sports',
    audience: 'All',
    summary: 'The 15th Annual Inter-House Athletics & Sports Competition is scheduled for October 15th at the school sports complex.',
    author: 'Sports Committee',
  },
]

export const INITIAL_AUDIT_LOGS = [
  { id: 1, timestamp: '2025-09-16 10:14:22', user: 'Admin User (Admin)', action: 'Fee Payment Approved', entity: 'Payment #INV-2025-001', ip: '192.168.1.45', status: 'Success' },
  { id: 2, timestamp: '2025-09-16 09:45:10', user: 'Admin User (Admin)', action: 'Student Profile Updated', entity: 'Student #RS-0001', ip: '192.168.1.45', status: 'Success' },
  { id: 3, timestamp: '2025-09-16 08:30:04', user: 'James Okafor (Teacher)', action: 'Attendance Submitted', entity: 'Class JSS 1 (52 records)', ip: '192.168.1.102', status: 'Success' },
  { id: 4, timestamp: '2025-09-15 16:22:18', user: 'System (Automated)', action: 'Nightly Database Backup', entity: 'PostgreSQL Database Dump', ip: '127.0.0.1', status: 'Success' },
  { id: 5, timestamp: '2025-09-15 14:10:55', user: 'Admin User (Admin)', action: 'Admission Letter Issued', entity: 'Candidate #ADM-2025-003', ip: '192.168.1.45', status: 'Success' },
  { id: 6, timestamp: '2025-09-15 11:05:32', user: 'Security System', action: 'Failed Login Attempt', entity: 'Username: unknown_guest', ip: '102.89.23.11', status: 'Warning' },
]

export const INITIAL_SETTINGS = {
  school_name: 'Riverside Academy',
  motto: 'Excellence, Integrity, Leadership',
  domain: 'riversideacademy.com',
  current_session: '2025/2026',
  current_term: 'First Term',
  term_start: '2025-09-01',
  term_end: '2025-12-15',
  phone: '+234 800 RIVERSIDE',
  email: 'info@riversideacademy.com',
  address: 'Plot 14, Riverside Boulevard, Victoria Island, Lagos, Nigeria',
  currency: '₦ (NGN)',
  theme_color: '#09261d',
  enable_ai_analytics: true,
  sms_notifications: true,
  email_notifications: true,
  auto_backup_daily: true,
}

