# Generated by Django 6.1.1 on 2026-09-06 13:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0001_initial"),
        ("students", "0002_student_parents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="fee",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="fee_amount_non_negative"
            ),
        ),
    ]
