# Generated by Django 6.1.1 on 2026-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolprofile",
            name="hero_heading",
            field=models.CharField(
                default="Inspiring excellence, building futures.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="hero_subtext",
            field=models.TextField(
                default="Where every learner is seen, challenged, and prepared to make a meaningful difference in the world."
            ),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="name",
            field=models.CharField(default="Riverside Academy", max_length=200),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="tagline",
            field=models.CharField(default="Learning with purpose", max_length=200),
        ),
    ]
