# Generated by Django 6.1.1 on 2026-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0004_schoolprofile_theme_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='public_layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
