import { useState } from 'react'

function ParentHeader({ eyebrow, title, detail, onBack }) { return <div className="content-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{detail}</p></div>{onBack && <button className="secondary-button" onClick={onBack}>← Overview</button>}</div> }

function ParentWorkspace({ active, setActive, profile, data }) {
  const [selectedId, setSelectedId] = useState(data.children[0]?.id || '')
  const child = data.children.find((item) => String(item.id) === String(selectedId)) || data.children[0]
  const title = active === 'Overview' ? `Good day, ${profile?.first_name || 'parent'}` : active
  const detail = active === 'Overview' ? 'Choose a child to review their school day.' : `Showing ${active.toLowerCase()} for ${child?.full_name || 'your child'}.`
  
  if (!child) return <main className="content"><div className="content-heading"><div><p className="eyebrow">PARENT PORTAL</p><h1>{title}</h1><p className="muted">{detail}</p></div></div><section className="panel"><div className="empty-state"><strong>No children linked yet</strong><span>Ask the school to link a child to your account.</span></div></section></main>
  
  const records = active === 'Assignments' ? child.assignments || [] : active === 'Academics' || active === 'Exams & Grades' || active === 'Grades' ? child.grades || [] : active === 'Reports' ? child.reports || [] : []
  
  return <><ParentHeader eyebrow="PARENT PORTAL" title={title} detail={detail} onBack={active === 'Overview' ? null : () => setActive('Overview')} /><section className="panel parent-selector"><label>Child<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{data.children.map((item) => <option key={item.id} value={item.id}>{item.full_name} · {item.admission_number}</option>)}</select></label></section>{active === 'Overview' ? <section className="parent-grid"><section className="panel parent-card"><div className="student-cell"><div className="student-avatar green">{child.full_name.slice(0, 1)}</div><div><h2>{child.full_name}</h2><p className="panel-subtitle">{child.admission_number} · {child.email}</p></div></div><div className="student-summary"><div><span>Attendance</span><strong>{child.attendance?.percentage == null ? '—' : `${child.attendance.percentage}%`}</strong><small>{child.attendance?.total || 0} records</small></div><div><span>Average score</span><strong>{child.average_score == null ? '—' : child.average_score}</strong><small>Latest grades</small></div><div><span>Reports</span><strong>{child.reports?.length || 0}</strong><small>Available</small></div></div><div className="parent-card-actions"><button className="primary-button" onClick={() => setActive('Academics')}>View academics <span>→</span></button><button className="secondary-button" onClick={() => setActive('Attendance')}>View attendance</button></div></section></section> : active === 'Attendance' ? <section className="panel"><div className="student-summary"><div><span>Total Records</span><strong>{child.attendance?.total || 0}</strong><small>Evaluated</small></div><div><span>Present</span><strong>{child.attendance?.present || 0}</strong><small>Days</small></div><div><span>Percentage</span><strong>{child.attendance?.percentage == null ? '—' : `${child.attendance.percentage}%`}</strong><small>Attendance</small></div></div></section> : <section className="panel">{records.length ? records.map((record, index) => <div className="attention-item" key={record.id || index}><div><b>{record.title || record.grades__subject__name || record.date || `Record ${index + 1}`}</b><span>{record.due_date || record.status || record.grades__score || record.report_type || 'Available'}</span></div></div>) : <div className="empty-state"><strong>No {active.toLowerCase()} yet</strong><span>New child records will appear here when published.</span></div>}</section>}</>
}

export default ParentWorkspace
