# Generated by Django 6.1.1 on 2026-09-14 20:38

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/",
                        validators=[core.models.validate_file_size],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admission", "Admission"),
                            ("student_record", "Student Record"),
                            ("teacher_record", "Teacher Record"),
                            ("policy", "Policy"),
                            ("report_card", "Report Card"),
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("is_archived", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Can be accessed by anyone with a signed URL",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
