# Generated by Django 6.1.1 on 2026-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Riverside Academy', max_length=255)),
                ('address', models.CharField(default='12, Riverside Road, Lagos', max_length=255)),
                ('phone', models.CharField(default='+234 803 123 4567', max_length=50)),
                ('email', models.EmailField(default='info@riversideacademy.ng', max_length=254)),
                ('website', models.CharField(default='www.riversideacademy.ng', max_length=255)),
                ('motto', models.CharField(default='Knowledge, Character, Excellence', max_length=255)),
                ('academic_year', models.CharField(default='2025/2026', max_length=50)),
                ('school_code', models.CharField(default='RA-LOS-0042', max_length=50)),
                ('currency', models.CharField(default='NGN (₦)', max_length=50)),
                ('logo_data', models.TextField(blank=True, default='')),
                ('current_session', models.CharField(default='2025/2026', max_length=50)),
                ('current_term', models.CharField(default='1st Term', max_length=50)),
                ('term_start', models.CharField(default='2026-09-08', max_length=50)),
                ('term_end', models.CharField(default='2026-12-18', max_length=50)),
                ('midterm_start', models.CharField(default='2026-10-26', max_length=50)),
                ('midterm_end', models.CharField(default='2026-10-30', max_length=50)),
                ('min_attendance', models.IntegerField(default=85)),
                ('pass_mark', models.IntegerField(default=50)),
                ('ca1_weight', models.IntegerField(default=20)),
                ('ca2_weight', models.IntegerField(default=20)),
                ('test_weight', models.IntegerField(default=20)),
                ('exam_weight', models.IntegerField(default=40)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('fee_reminders', models.BooleanField(default=True)),
                ('absence_alerts', models.BooleanField(default=True)),
                ('exam_published_notice', models.BooleanField(default=True)),
                ('sms_sender_id', models.CharField(default='RIVERSIDE', max_length=50)),
                ('daily_attendance_cutoff', models.CharField(default='10:00 AM', max_length=50)),
                ('enforce_2fa', models.BooleanField(default=True)),
                ('session_timeout', models.CharField(default='30', max_length=50)),
                ('password_expiry_days', models.CharField(default='90', max_length=50)),
                ('require_special_char', models.BooleanField(default=True)),
                ('ip_whitelisting', models.BooleanField(default=False)),
                ('max_failed_attempts', models.IntegerField(default=5)),
                ('roles_config', models.JSONField(blank=True, default=list)),
                ('backups_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
