# Generated by Django 6.1.1 on 2026-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='theme_palette',
            field=models.CharField(default='emerald_gold', max_length=50),
        ),
    ]
